"""empty message

Revision ID: 6ea5574a9551
Revises: 
Create Date: 2020-01-20 10:18:45.319897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea5574a9551'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'ROOT', name='roletype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'APPROVED', 'UNAPPROVED', 'OUTDUE', name='meetingstatustype'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('key_words', sa.String(length=100), nullable=True),
    sa.Column('lang', sa.Enum('CN', 'EN', name='meetinglanguagetype'), nullable=True),
    sa.Column('contact', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('introduction', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['register'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewer'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
